### ISSUE TITLE
Swagger-UI for /api-docs does not work on safari

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#111]
On safari, the JS code for authentication of API requests is not working as expected.  (It does work on Firefox).  The swagger-ui should work on:
- [x] Firefox
- [ ] Safari
- [x] Chrome
- [ ] Other browsers?

**Comment by Pcolar** [comment]
I am using Chrome exclusively for access to the Swagger API. Endpoints (Bag, Node, Replication, Member) are working as expected.

**Comment by Pcolar** [comment]
This is an open issue in swagger-ui 2.0, but I don't see anything specific to Safari.   https://github.com/swagger-api/swagger-ui/issues/2263
