### ISSUE TITLE
Adapter#map_bool creates missing params - bug in /ingest

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#114]
The `params[:ingested]` is set to `false` by default, it seems, so a generic call to `/ingest` is always going to return only `false` ingest records?  Is that a “feature”?

https://github.com/dpn-admin/dpn-server/blob/develop/app/adapters/ingest_adapter.rb#L12 seems to ensure that when `params[:ingested] == nil`, it becomes `false`.  In the general case where the raw HTTP params has no key for `ingested`, it will return `nil` for `params[:ingested]`.  Maybe `map_bool` needs to first check `params.keys.include?` before assigning a value?  See
- https://github.com/dpn-admin/dpn-server/blob/develop/app/adapters/adapter.rb#L31-L42

When there is some `ingest` fixture data loaded, where the record has `ingested: true`, e.g.

```
$ node=sdr
$ RAILS_ENV="impersonate_$node" IMPERSONATE=$node bundle exec rails c
Loading impersonate_sdr environment (Rails 4.2.7.1)
irb(main):001:0> Ingest.all
  Ingest Load (0.4ms)  SELECT `ingests`.* FROM `ingests`
=> #<ActiveRecord::Relation [#<Ingest id: 298216875, ingest_id: "51cae6e3-63d1-41a3-b4dc-7d021a918d6f", bag_id: 368674721, ingested: true, created_at: "2015-09-15 17:56:03">]>
```

The REST API call is not returning it, e.g.

```
$ node=sdr
$ RAILS_ENV="impersonate_$node" IMPERSONATE=$node bundle exec rails s
$ curl -L -H 'Authorization: Token token=sdr_token' http://localhost:3000/api-v2/ingest
{"count":0,"next":null,"previous":null,"results":[]}
```

So, this is handled in
https://github.com/dpn-admin/dpn-server/blob/develop/app/controllers/ingests_controller.rb#L15-L24

Some debugging indicates that it fails to find the record because `params[:ingested]` is set to `false`, even when that param is not given or required.

**Comment by dazza-codes** [comment]
Unfortunately, this is a symptom of too much abstraction without enough specificity in the unit tests on the controller and all the permutations on the db-values and HTTP request params.  Looking quickly at the code in the controller and the adapter, there is no clear or simple way to make a change to the code without significant concern about breaking something else.  If the use-case that is identified in this bug report were part of the unit tests in the first place, the abstraction in the adapter(s) would have failed.  Similar bugs may be present in other controllers, given the level of abstraction that this bug reveals.

**Comment by malakai97** [comment]
Controller tests are integration tests.  Insufficient testing of the controllers is likely a code smell that indicates the logic should be handled somewhere else where it is easier to test.
