### ISSUE TITLE
script/migrate_cluster.rb cannot find cipher_key

### ISSUE THREAD

**Issue by malakai97** [dpn-admin/dpn-server#134]
Running the script (in order, as described in Cluster.md) generates the error:
```
NoMethodError: undefined method `cipher_key' for #<Rails::Application::Configuration:0x0055f9d26a3d90>
```

The configuration files are configured correctly, so this is due to the script setting RAILS_ENV to the wrong value.

**Comment by dazza-codes** [comment]
Should be fixed by #135, leave to @malakai97 to confirm and close this bug.
