### ISSUE TITLE
replication transfer query does not use bag UUID to restrict result set

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#137]
Here's an example, using the `dpn-client` gem in a ruby console for the DPN-dev network:
```
> query
=> {:page_size=>50, :bag=>"0089f171-5cf8-4c4f-bfd4-3b6544ee8ab4", :from_node=>"chron", :to_node=>"sdr"}
> replications = []
> chron_node.dpn_client.replications(query) {|response| replications << response.body }
> replications.map {|repl| repl[:bag]}.uniq
=> ["a32e18e4-8bf4-4bc0-9e98-3f51da9ea2a1",
 "6f31995a-bf8d-4093-9f8c-b16a8f00288d",
 "1f806acb-52be-40d8-a9f9-2b6891cc62cf",
 "6b0f0fbf-f1b6-412e-b2f7-db6f35ff7154",
 "44023f57-e131-437d-be94-8d756fa2b8e5",
 "0d7ddb79-8f63-4ce3-8c90-f8452c6386fe",
 "a41f2d72-185a-4b81-bb1d-b90f907ecc7a",
 "60d28964-d18f-466a-8736-f2ceab3d320a",
 "d24e9708-6bef-432d-a1f4-df0955e79c9b"]
```

Notice how the query is returning repl-transfers with a lot of various bag-uuid values that are not the same as the bag-uuid in the query.

**Comment by dazza-codes** [comment]
The related code in the `dpn-client` project is at
https://github.com/dpn-admin/dpn-client/blob/master/lib/dpn/client/agent/replicate.rb#L18

That request should be routed and handled by this controller in `dpn-server`:
https://github.com/dpn-admin/dpn-server/blob/develop/app/controllers/replication_transfers_controller.rb#L16-L31

The adapter for the bag-uuid parameter should be:
https://github.com/dpn-admin/dpn-server/blob/develop/app/adapters/replication_transfer_adapter.rb#L20

**Comment by malakai97** [comment]
Seems like a bug in dpn-client; adding `it_behaves_like "a queryable endpoint", :bag` to the replication_transfers_controller_spec produces green tests.

**Comment by dazza-codes** [comment]
Maybe the adapter mapping should be translating the `bag` param into `bag_id`?
https://github.com/dpn-admin/dpn-server/blob/develop/app/adapters/replication_transfer_adapter.rb#L20

**Comment by dazza-codes** [comment]
Or the controller should be using `param[:bag]` instead of `param[:bag_id]`?
https://github.com/dpn-admin/dpn-server/blob/develop/app/controllers/replication_transfers_controller.rb#L19

**Comment by malakai97** [comment]
I did not test your hypotheses, but this appears to be due to the redirect from having a page_size > max stripping away the rest of the query parameters.

**Comment by malakai97** [comment]
Do you have the actual request that rails received?

**Comment by dazza-codes** [comment]
Sorry, have not looked at this in a dpn-server console/debug/logs yet (busy looking at something else).

**Comment by malakai97** [comment]
After investigating several hunches, I've realized that I'm not able to reproduce this.  

In a dev environment, I first created several replication transfers between the two nodes.  Afterwards, with a rails console on one terminal and a rails server on the other, I'm getting the correct result set.

This is what the server sees, and the incoming side looks correct:

``` ruby
{"method":"GET","path":"/api-v2/replicate","format":"*/*","controller":"ReplicationTransfersController","action":"index","status":200,"duration":61.02,"view":24.53,"db":2.41,"params":{"_json":null,"page_size":"50","bag":"89f02580-7a8f-43cf-85c8-48e3efbcd8e7","from_node":"chron","to_node":"sdr","page":"1","replication_transfer":{}},"@timestamp":"2016-11-03T21:01:54.665Z","@version":"1","message":"[200] GET /api-v2/replicate (ReplicationTransfersController#index)"}
```

And the return

``` ruby
[#<DPN::Client::Response:0x00556ac62fb4e0
  @body=
   {:replication_id=>"d34ccabc-5392-4e7d-8320-8f0f6cb8811a",
    :fixity_nonce=>"Us2lI89",
    :fixity_value=>nil,
    :cancel_reason=>nil,
    :cancel_reason_detail=>nil,
    :link=>"http://heidenreich.org/yoshiko.lind",
    :created_at=>"2016-10-03T21:00:14Z",
    :updated_at=>"2016-10-03T21:00:14Z",
    :store_requested=>false,
    :stored=>false,
    :cancelled=>false,
    :bag=>"89f02580-7a8f-43cf-85c8-48e3efbcd8e7",
    :fixity_algorithm=>"rg6tialxidz",
    :protocol=>"bjk4vyw7hrc",
    :from_node=>"chron",
    :to_node=>"sdr"},
  @status=200>]

```

Are you only seeing this in production?

**Comment by dazza-codes** [comment]
The code snippet in this issue description was based on a query/response from Chron-dev node (which should be running a RAILS_ENV=production?)

Here's the same query on the Chron-dev node using curl instead of `dpn-client`:

```
[dpn@dpn-dev ~]$ curl -L -X GET --header 'Accept: application/json' --header "Authorization: Token token=${CHRON_TOKEN}" 'https://dpn-registry-dev.ucsd.edu/api-v2/replicate/?bag=0089f171-5cf8-4c4f-bfd4-3b6544ee8ab4&from_node=chron&to_node=sdr'
{"count":9,"next":null,"previous":null,"results":[{"replication_id":"8483a652-0074-4c33-a1ca-ca5efdb67cb8","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/a32e18e4-8bf4-4bc0-9e98-3f51da9ea2a1.tar","created_at":"2016-11-02T15:35:53Z","updated_at":"2016-11-02T15:35:53Z","store_requested":false,"stored":false,"cancelled":false,"bag":"a32e18e4-8bf4-4bc0-9e98-3f51da9ea2a1","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"19d02190-ff55-4e31-bd2a-6b77a536f9ec","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/6f31995a-bf8d-4093-9f8c-b16a8f00288d.tar","created_at":"2016-11-02T15:35:55Z","updated_at":"2016-11-02T15:35:55Z","store_requested":false,"stored":false,"cancelled":false,"bag":"6f31995a-bf8d-4093-9f8c-b16a8f00288d","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"c26d55c7-4679-495d-9b72-78fd2b72535b","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/1f806acb-52be-40d8-a9f9-2b6891cc62cf.tar","created_at":"2016-11-02T15:35:58Z","updated_at":"2016-11-02T15:35:58Z","store_requested":false,"stored":false,"cancelled":false,"bag":"1f806acb-52be-40d8-a9f9-2b6891cc62cf","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"5b9fe1da-3005-49ef-8ec9-8da4c90500ce","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/6b0f0fbf-f1b6-412e-b2f7-db6f35ff7154.tar","created_at":"2016-11-02T15:35:59Z","updated_at":"2016-11-02T15:35:59Z","store_requested":false,"stored":false,"cancelled":false,"bag":"6b0f0fbf-f1b6-412e-b2f7-db6f35ff7154","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"101e61ae-0a9c-4ed5-b74f-995af0689134","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/44023f57-e131-437d-be94-8d756fa2b8e5.tar","created_at":"2016-11-02T15:35:59Z","updated_at":"2016-11-02T15:35:59Z","store_requested":false,"stored":false,"cancelled":false,"bag":"44023f57-e131-437d-be94-8d756fa2b8e5","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"b0cc4003-6b06-4f15-9ce5-bc22a56b0f81","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/0d7ddb79-8f63-4ce3-8c90-f8452c6386fe.tar","created_at":"2016-11-02T15:36:00Z","updated_at":"2016-11-02T15:36:00Z","store_requested":false,"stored":false,"cancelled":false,"bag":"0d7ddb79-8f63-4ce3-8c90-f8452c6386fe","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"eeb01739-eafb-46ac-a529-eb3dbbb5e451","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/a41f2d72-185a-4b81-bb1d-b90f907ecc7a.tar","created_at":"2016-11-02T15:36:03Z","updated_at":"2016-11-02T15:36:03Z","store_requested":false,"stored":false,"cancelled":false,"bag":"a41f2d72-185a-4b81-bb1d-b90f907ecc7a","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"f5e6d6a8-1998-4163-aa77-81cb0634b453","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/60d28964-d18f-466a-8736-f2ceab3d320a.tar","created_at":"2016-11-02T15:36:03Z","updated_at":"2016-11-02T15:36:03Z","store_requested":false,"stored":false,"cancelled":false,"bag":"60d28964-d18f-466a-8736-f2ceab3d320a","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"},{"replication_id":"286cfba3-d986-459b-9870-eaac3b328b43","fixity_nonce":null,"fixity_value":null,"cancel_reason":null,"cancel_reason_detail":null,"link":"sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/d24e9708-6bef-432d-a1f4-df0955e79c9b.tar","created_at":"2016-11-02T15:36:04Z","updated_at":"2016-11-02T15:36:04Z","store_requested":false,"stored":false,"cancelled":false,"bag":"d24e9708-6bef-432d-a1f4-df0955e79c9b","fixity_algorithm":"sha256","protocol":"rsync","from_node":"chron","to_node":"sdr"}]}
```

One of the responses has `"bag":"d24e9708-6bef-432d-a1f4-df0955e79c9b"`, which is not what was requested in the bag filter (`0089f171-5cf8-4c4f-bfd4-3b6544ee8ab4`).

**Comment by dazza-codes** [comment]
This bug _might_ be an artifact of issuing a query for a bag in the local-node that no longer exists in the remote-node.  This is a scenario that should be impossible in DPN, but might arise in the DPN-dev network because a node wipes the db at some point after some of it's registry is replicated elsewhere.  For example, SDR-dev has some bags from Chron-dev that are subsequently removed from the Chron-dev system.

To check this again, some queries were issued for replication transfers with bags that currently exist on Chron-dev.  To check this, first query for any repl-transfers where the from_node=chron and the to_node=sdr:

```
$ curl -L -X GET --header 'Accept: application/json' --header "Authorization: Token token=${CHRON_TOKEN}" 'https://dpn-registry-dev.ucsd.edu/api-v2/replicate/?from_node=chron&to_node=sdr'
{"count":9,"next":null,"previous":null,"results":[{"replication_id":"8483a652-0074-4c33-a1ca-ca5efdb67cb8", ...},{"replication_id":"19d02190-ff55-4e31-bd2a-6b77a536f9ec",...},... snipped ...]}
```

Then identify some `bag` UUIDs in these repl-transfers and issue a query that is constrained to one of them, e.g.:

```
$ curl -L -X GET --header 'Accept: application/json' --header "Authorization: Token token=${CHRON_TOKEN}" 'https://dpn-registry-dev.ucsd.edu/api-v2/replicate/?bag=d24e9708-6bef-432d-a1f4-df0955e79c9b&from_node=chron&to_node=sdr'
{"count":1,"next":null,"previous":null,"results":[
{"replication_id":"286cfba3-d986-459b-9870-eaac3b328b43", ... ,
  "bag":"d24e9708-6bef-432d-a1f4-df0955e79c9b", ... ,
  "from_node":"chron","to_node":"sdr"}]}
```

```
$ curl -L -X GET --header 'Accept: application/json' --header "Authorization: Token token=${CHRON_TOKEN}" 'https://dpn-registry-dev.ucsd.edu/api-v2/replicate/?bag=1f806acb-52be-40d8-a9f9-2b6891cc62cf&from_node=chron&to_node=sdr'
{"count":1,"next":null,"previous":null,"results":[
{"replication_id":"c26d55c7-4679-495d-9b72-78fd2b72535b", ... ,
  "bag":"1f806acb-52be-40d8-a9f9-2b6891cc62cf", ... ,
  "from_node":"chron","to_node":"sdr"}]}
```

**Comment by dazza-codes** [comment]
Using the oldest bag available in SDR-dev from the Chron-dev node, these queries illustrate an issue to resolve.

```
$ curl -v -L -X GET --header 'Accept: application/json' --header "Authorization: Token token=${CHRON_TOKEN}" ‘https://dpn-registry-dev.ucsd.edu/api-v2/bag/e800b2e2-401b-4c42-a883-747761f4c2a4’
… 
< HTTP/1.1 404 Not Found
...

$ curl -L -X GET --header 'Accept: application/json' --header "Authorization: Token token=${CHRON_TOKEN}" ‘https://dpn-registry-dev.ucsd.edu/api-v2/replicate/?bag=e800b2e2-401b-4c42-a883-747761f4c2a4&from_node=chron&to_node=sdr’
{”count”:9,  … }
```

The first query shows that the bag no longer exists in Chron-dev (a problem in itself, but let's ignore that for now).  The second query shows that the result set contains too many repl-transfer items for a bag that does not exist.  One argument is: that result set should be empty.  Is this a bug to fix?

**Comment by dazza-codes** [comment]
So, an informed guess at what is going on here:
- adapter tries to locate the bag-uuid in the bag model and fails, so it assigns `nil` to the param?  (That is, it cannot return a bag model instance or a bag_id that doesn't exist.  It does not raise an AR exception for a bag not found.  It returns `nil` instead.)
- when AR gets a `nil` param, it just ignores it in the `where` filtering?
  - so, this boils down to what is `.with_bag_id(params[:bag_id])` when the bag doesn't exist?

```
$ BAG=123  # this doesn't exist, for sure
$ curl -L -X GET --header 'Accept: application/json' --header "Authorization: Token token=${CHRON_TOKEN}" 'https://dpn-registry-dev.ucsd.edu/api-v2/replicate/?bag=${BAG}&from_node=chron&to_node=sdr'
{"count":9, ... }
```

**Comment by malakai97** [comment]
> when AR gets a nil param, it just ignores it in the where filtering?
> The scope has a specific test for `id.blank?`.  

The scope is `with_bag_id`, and there's no way with just an `:id` field to differentiate between a request for an id that doesn't exist, and one for nil.  So a fix would involve (1) changing that scope to accept a Bag object, (2) changing the controller to pass the Bag object instead of the bag_id, and (3) the adapter to not convert to a bag_id, but rather just a bag.

Of those:
1. Is trivial if AR supports that kind of `where` out of the box, and is still pretty simple otherwise.
2. Is trivial
3. This bit of code right now (in map_belongs_to) actually searched for the record, then if it found it sets the params[:bag_id] to the found object's `:id`, otherwise it sets it to nil.  Changing this to both set params[:bag] to the object and instantiate a new, unsaved record if it can't find one isn't too hard.

I can't get to this today but I should have some time tomorrow.  I expect there will be multiple places where this bug is present for similar fields.

**Comment by malakai97** [comment]
Implementation of the above fix in https://github.com/dpn-admin/dpn-server/pull/141

This is opposed to the alternative, "simpler" fix of the adapters returning a special integer value (e.g. any negative value) instead of nil to force the scopes to generate the correct relation instead of an empty one.  I felt the version in #141 would be more robust going forward.
