### ISSUE TITLE
Review node replication configurations

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#138]
Review the node replication and restore configurations for:
- replicate_from
- replicate_to
- restore_from
- restore_to

```ruby
# APTrust
{
 "replicate_from":["tdr","hathi","chron"],
 "replicate_to":["tdr","hathi","chron"],
 "restore_from":["tdr","hathi","chron"],
 "restore_to":["tdr","hathi","chron"]
}

# Chronopolis
{
 "replicate_from":["hathi","sdr","tdr","aptrust"],
 "replicate_to":["hathi","sdr","tdr","aptrust"],
 "restore_from":["hathi","sdr","tdr","aptrust"],
 "restore_to":["hathi","sdr","tdr","aptrust"]
}

# Hathi-Trust
{
 "replicate_from":["aptrust","tdr","hathi","chron","sdr"],
 "replicate_to":["aptrust","tdr","hathi","chron","sdr"],
 "restore_from":["aptrust","tdr","hathi","chron","sdr"],
 "restore_to":["aptrust","tdr","hathi","chron","sdr"]
}

# Stanford
{
 "replicate_from":[],
 "replicate_to":[],
 "restore_from":[],
 "restore_to":[]
}

# Texas
{
 "replicate_from":[],
 "replicate_to":[],
 "restore_from":[],
 "restore_to":[]
}
```

**Comment by dazza-codes** [comment]
Updated SDR-dev:

``` ruby
# Stanford
{
 "replicate_from":["hathi","chron","tdr","aptrust"],
 "replicate_to":[],
 "restore_from":[],
 "restore_to":["tdr","chron","hathi","aptrust"]
}
```

Although the restore functionality is not implemented, at this stage.

**Comment by smutniak** [comment]
```
rest-dev.lib.utexas.edu
"replicate_from": [ "hathi", "sdr","chron", "aptrust"],
"replicate_to": ["hathi","sdr", "chron","aptrust"],
"restore_from": [ "hathi", "sdr","chron","aptrust"],
"restore_to": ["hathi", "sdr", "chron","aptrust"],
```

**Comment by dazza-codes** [comment]
When I check SDR-dev just now, it has different settings than what was explicitly set, i.e.

``` ruby
# Stanford
{
  "replicate_from":["hathi","chron","tdr"],
  "replicate_to":["chron","tdr","hathi"],
  "restore_from":["chron","tdr","hathi"],
  "restore_to":["tdr","chron","hathi"]
}
```

As a guess, something about saving an update of the Node data when details are retrieved from a remote node has changed these settings on the `sdr` node.  (Not sure if that is desired behavior or a side-effect bug?)

**Comment by mikejritter** [comment]
Just seeing this now but I figure we should have some discussion on these. For our production service I use the `replicate_to` field to choose which nodes to create replications for, so I'm continually updating mine as nodes come on and offline (note: not unexpected/planned downtime, but something like hathi where the node is offline until 2.0).

At the moment our entry on `dpn-registry.ucsd.edu` looks like:
```
{
  "replicate_from": [],
  "replicate_to": [
    "aptrust",
    "tdr"
  ],
  "restore_from": [],
  "restore_to": []
}
```
so it looks as though it should be updated for who I replicate from.

Also a general question - in the future will we want to validate these (and how)? i.e. node_a `replicate_to` = `[node_b]`, so node_b `replicate_from` MUST contain `node_a`.

**Comment by malakai97** [comment]
> As a guess, something about saving an update of the Node data when details are retrieved from a remote node has changed these settings on the sdr node. (Not sure if that is desired behavior or a side-effect bug?)

Indeed, creating a replicate_to automatically creates the replication_from on the other node, which allows nodes to coerce support.  We can probably address this by modifying the way the associations function, but it could require separate associations and separate join tables.  I'll create a bug.
