### ISSUE TITLE
DPN-dev inconsistent fixity algs

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#139]
During node-sync ops, there are failures to update node data because there are inconsistent fixity algorithms across DPN-dev nodes.  Some nodes have both `md5` and `sha256`, some have only `sha256` and some have none.  For example, the SDR-dev logs show some details:

- hathi-dev has `"protocols":null,"fixity_algorithms":null`
- tdr-dev has `"protocols":["rsync"],"fixity_algorithms":["md5","sha256"]`

Because sdr-dev has only `sha256`, the node update (PUT) operation for tdr-dev is failing because it cannot update that nodes fixity algorithm (the adapter for this parameter fails to find a corresponding `md5` fixity-alg model (or ID).

```
I, [2016-11-09T10:33:15.319144 #17067]  INFO -- : {"method":"PUT","path":"/api-v2/node/tdr","format":"*/*","controller":"NodesController","action":"update","status":500,"error":"ActiveRecord::AssociationTypeMismatch: FixityAlg(#44247480) expected, got NilClass(#9191380)","duration":38.92,"view":0.0,"db":15.39,"params":{"namespace":"tdr","api_root":"https://rest-dev.lib.utexas.edu/","auth_credential":"2c6b85a3-a442-401c-b331-8edd293f0bcc","name":"tdr","ssh_pubkey":null,"created_at":"2016-11-08T16:11:02Z","updated_at":"2016-11-08T17:05:21Z","replicate_from":["hathi","sdr","chron","aptrust"],"replicate_to":["hathi","sdr","chron","aptrust"],"restore_from":["hathi","sdr","chron","aptrust"],"restore_to":["hathi","sdr","chron","aptrust"],"protocols":["rsync"],"fixity_algorithms":["md5","sha256"],"storage":{"region":"default","type":"default"},"node":{"namespace":"tdr","name":"tdr","ssh_pubkey":null,"created_at":"2016-11-08T16:11:02Z","updated_at":"2016-11-08T17:05:21Z","api_root":"https://rest-dev.lib.utexas.edu/","auth_credential":"2c6b85a3-a442-401c-b331-8edd293f0bcc"}},"@timestamp":"2016-11-09T18:33:15.316Z","@version":"1","message":"[500] PUT /api-v2/node/tdr (NodesController#update)"}
F, [2016-11-09T10:33:15.321768 #17067] FATAL -- :
ActiveRecord::AssociationTypeMismatch (FixityAlg(#44247480) expected, got NilClass(#9191380)):
  app/models/node.rb:160:in `set_attributes_with_associations'
  app/models/node.rb:57:in `update_with_associations'
  app/controllers/nodes_controller.rb:43:in `update'


I, [2016-11-09T10:33:15.556857 #17067]  INFO -- : {"method":"PUT","path":"/api-v2/node/hathi","format":"*/*","controller":"NodesController","action":"update","status":200,"duration":108.88,"view":13.68,"db":25.88,"params":{"namespace":"hathi","api_root":"https://staging.dpn.hathitrust.org/","auth_credential":"920a81f11ba949979c2a743cfcc0edbd0841228838e2ceef64ed858ae81f515380016031cba10f9c76809264fb994c5afe1c0bf71c88b0999ac1bd9b36936afa","name":"HathiTrust","ssh_pubkey":null,"created_at":"2016-10-17T19:01:22Z","updated_at":"2016-10-17T19:03:33Z","replicate_from":["aptrust","tdr","hathi","chron","sdr"],"replicate_to":["aptrust","tdr","hathi","chron","sdr"],"restore_from":["aptrust","tdr","hathi","chron","sdr"],"restore_to":["aptrust","tdr","hathi","chron","sdr"],"protocols":null,"fixity_algorithms":null,"storage":{"region":"default","type":"default"},"node":{"namespace":"hathi","name":"HathiTrust","ssh_pubkey":null,"created_at":"2016-10-17T19:01:22Z","updated_at":"2016-10-17T19:03:33Z","api_root":"https://staging.dpn.hathitrust.org/","auth_credential":"920a81f11ba949979c2a743cfcc0edbd0841228838e2ceef64ed858ae81f515380016031cba10f9c76809264fb994c5afe1c0bf71c88b0999ac1bd9b36936afa"}},"@timestamp":"2016-11-09T18:33:15.556Z","@version":"1","message":"[200] PUT /api-v2/node/hathi (NodesController#update)"}
```

--- 

(Checklist added by @malakai97)

Protocols conforming to dpn-rest-spec/standard.md:

- [x] aptrust-dev
- [x] chron-dev
- [x] hathi-dev
- [x] sdr-dev
- [x] tdr-dev

Fixity algorithms conforming to dpn-rest-spec/standards.md:

- [x] aptrust-dev
- [x] chron-dev (has md5)
- [x] hathi-dev (has md5)
- [x] sdr-dev
- [x] tdr-dev (has md5)

**Comment by dazza-codes** [comment]
This can be fixed by simply adding `md5` to the sdr-dev db (done), but it does raise questions about registry-data synchronization (complexity/constraints).  What appears to be the case is that sdr-dev cannot remove support for `md5` independently of other DPN nodes, without losing the ability to update/sync the registry node-config data from other nodes.  Does the DPN-spec require that every node in the network MUST support all the same fixity algorithms and protocols etc?

**Comment by dazza-codes** [comment]
- aptrust-dev:
  - `"protocols":["rsync"],"fixity_algorithms":["sha256"]`
- chron-dev:
  - `"protocols":["rsync"],"fixity_algorithms":["sha256","md5"]`
- hathi-dev:
  - `"protocols":null,"fixity_algorithms":null`
- sdr-dev:
  - `"protocols":["rsync"],"fixity_algorithms":["sha256"]`
  - `md5` was added by using rails console and `FixityAlg.new` etc. but it does not show up in /node/sdr reponse from API.
- tdr-dev:
  - `"protocols":["rsync"],"fixity_algorithms":["md5","sha256"]`

**Comment by malakai97** [comment]
Nodes should not support md5 at this time.  It's probably my fault that some do, given what was in the seeds files.

Additionally, attempting to synchronize a node that has a fixity_alg/protocol/etc that is not supported in dpn-rest-spec/Standards.md _should_ fail.  The alternative is automatically creating the records for those unsupported values, which has the negative effect of allowing nodes to mint arbitrary protocols/fixity_algs/etc.

**Comment by dazza-codes** [comment]
Removed `md5` from SDR-dev node.

**Comment by dazza-codes** [comment]
The DPN BagIt only supports `sha256`; it raises an exception for anything else, see
- https://github.com/dpn-admin/dpn-bagit/blob/master/lib/dpn/bagit/bag.rb#L32-L50
- https://github.com/dpn-admin/dpn-bagit/blob/master/lib/dpn/bagit/serialized_bag.rb#L38-L50

**Comment by smutniak** [comment]
md5 removed from tdr's rest-dev

**Comment by mikejritter** [comment]
md5 removed from chron-dev

**Comment by malakai97** [comment]
Resolved.
