### ISSUE TITLE
replication_transfer GET response could include `bag_id`?

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#23]
The replication_transfer GET response includes a `uuid` value, which seems to correspond to a bag UUID.  A replication_transfer POST invokes validation that requires a `bag_id` value.
- https://github.com/dpn-admin/dpn-server/blob/master/app/models/replication_transfer.rb#L106
- https://github.com/dpn-admin/dpn-server/blob/master/app/models/replication_transfer.rb#L123

So, perhaps the GET response `uuid` could be `bag_id` instead (or copied to `bag_id`)?  If it were, it could be easier to directly create/update the replication_transfer using the GET response in a corresponding POST/PUT request.  The related code seems to be in
https://github.com/dpn-admin/dpn-server/blob/master/app/adapters/replication_transfer_adapter.rb#L15

For example, a GET response for some fixity data looks like this:

``` ruby
{:replication_id=>"20000000-0000-4000-a000-000000000007",
 :fixity_nonce=>nil,
 :fixity_value=>nil,
 :fixity_accept=>false,
 :bag_valid=>true,
 :status=>"requested",
 :link=>"/data/src/dlss/dpn/dpn-server/test/fixtures/integration/testbags/00000000-0000-4000-a000-000000000002.tar",
 :created_at=>"2015-09-15T19:38:31Z",
 :updated_at=>"2015-09-15T19:38:31Z",
 :uuid=>"00000000-0000-4000-a000-000000000002",
 :fixity_algorithm=>"sha256",
 :protocol=>"rsync",
 :from_node=>"chron",
 :to_node=>"aptrust"}
```

This response is derived from the fixity data at
https://github.com/dpn-admin/dpn-server/blob/master/test/fixtures/integration/chron/replication_transfers.yml#L15-L27

Notice how it no longer contains the `bag: chron01` value and it has added some values, including the `uuid` that corresponds to a `bag_id` for the POST validations.

**Comment by dazza-codes** [comment]
Perhaps the adapter could use something like (I don't yet properly understand adapters):

``` ruby
map_to_public :uuid do |id|
  { bag_id: id }
end
map_from_public :bag_id do |id|
  Bag.find_by(uuid: id)
end
```

**Comment by mikejritter** [comment]
I had talked to Bryan about this and I believe we reached a similar conclusion (in addition to talking about the lack of uniform identifying between classes). It also looks like much the documentation (both old and new) are incorrect. The dpn-rest-wiki  and swagger docs show:

```
{
            "from_node": "aptrust",
            "to_node": "chron",
            "bag": "cfd167a0-baad-4235-b896-041e710e6c62",
           ...
}
```

but the actual response when testing contains the `uuid` field that you've mentioned.

I've been taking a look at the adapters recently to try and understand them myself, and can look into updating the replication_adapter to provide a more descriptive key. I think it will mostly come down to what we want to update it to - it looks like `bag` is already in most of the docs so that's also a possibility.

**Comment by dazza-codes** [comment]
Note to self:  when this is revised, I need to modify this commit at
https://github.com/sul-dlss/dpn-sync/commit/010cb9607f2d597363f19925c4491f4b9b5e2ce5

**Comment by dazza-codes** [comment]
If my guess at the adpater above is close and we adopt `bag` as the key, we get:

``` ruby
map_to_public :uuid do |id|
  { bag: id }
end
map_from_public :bag do |id|
  Bag.find_by(uuid: id)
end
```

**Comment by mikejritter** [comment]
It's actually a bit simpler in the replication_adapter:

```
diff --git a/app/adapters/replication_transfer_adapter.rb b/app/adapters/replication_transfer_adapter.rb
index 855fa5a..68d512d 100644
--- a/app/adapters/replication_transfer_adapter.rb
+++ b/app/adapters/replication_transfer_adapter.rb
@@ -15,7 +15,7 @@ class ReplicationTransferAdapter < ::AbstractAdapter
   map_simple :status, :status
   map_simple :link, :link

-  map_belongs_to :bag, :uuid
+  map_belongs_to :bag, :bag, sub_method: :uuid
   map_belongs_to :fixity_alg, :fixity_algorithm, sub_method: :name
   map_belongs_to :protocol, :protocol, sub_method: :name
   map_belongs_to :from_node, :from_node, model_class: Node, sub_method: :namespace
```

`map_belongs_to` does the lookup for us in the db and adds it to the public_fields (in adapter.rb).

Digging around a little bit more, I see that the newer models (message_digest_adapter, ingest_adapter, and fixity_check_adapter) all have the belongs_to relation as shown in my diff using `bag` in place of `uuid`. The restore_adapter has the old relation, and should be updated as well.

**Comment by mikejritter** [comment]
I went with `bag` in both the replication and restore transfer adapters to be in line with the other adapters. Updated the specs to be in line with the new schemas as well, all of which is now on the develop branch.
