### ISSUE TITLE
Bag transfer issues for api-v2

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#61]
_From @darrenleeweber on September 2, 2016 18:46_

@diamondap says, at https://internet2.slack.com/archives/i2-dpn-developers/p1472841471000477,
- [x] 1. dpn-server should set StoreRequested to true on replication transfers when the to_node returns a good fixity value.
- [x] 2. we should have a vocabulary for the CancelReason field of the transfer (bad fixity, bag invalid, error on replicating node, no space on replicating node, other).
- [ ] 3. possibly add a new field to ReplicationTransfer called cancel_reason_detail, where we can store free-form text describing why the transfer was cancelled.

This might be split out into separate issues.

_Copied from original issue: sul-dlss/dpn-server#5_

**Comment by dazza-codes** [comment]
_From @malakai97 on September 2, 2016 18:49_

For 1, use [ActiveRecord::Observer](https://github.com/rails/rails-observers)

**Comment by malakai97** [comment]
1. opened as #63 
2. opened as #62 
3. opened as #64
