### ISSUE TITLE
Add ReplicationTransfer#cancel_reason_detail

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#64]
_From @darrenleeweber on September 2, 2016 18:57_

From #61 
- [ ] possibly add a new field to ReplicationTransfer called cancel_reason_detail, where we can store free-form text describing why the transfer was cancelled.

_Copied from original issue: sul-dlss/dpn-server#8_

**Comment by malakai97** [comment]
See #77

**Comment by dazza-codes** [comment]
This is done.
