### ISSUE TITLE
Evaluate adding a swagger UI interface

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#65]
e.g. https://github.com/batdevis/swagger_engine

**Comment by dazza-codes** [comment]
WIP on `swagger-ui` branch.

**Comment by smutniak** [comment]
Is the purpose to keep a convenient API reference included with dpn-server or something more?

**Comment by dazza-codes** [comment]
This is an evaluation of including swagger-ui in the dpn-server app, as a rails engine.  The purpose is several, really.  Firstly, to evaluate whether the swagger.{yaml | json} spec file is accurate; that is, it should work when the swagger-ui is correctly hooked up with a dpn-server app.  A couple of changes to the spec doc have been found as a result of this.  (Mike is updating the doc.)  Secondly, the swagger-ui displays the API as a good reference, but it can be a functional tool for inspecting data or interacting with the API.  To enable this, it must be locked down by authorization and the token authentication must be enabled.  In the `swagger-ui` branch, there is something that is close to working, but it requires some JS tweaks that will be supplied by the `dpn_swagger_engine` when it's ready (soon).

**Comment by Pcolar** [comment]
I'm in favor of merging this into v2.0 as a tool set addition. Open to opposing viewpoints!

**Comment by dazza-codes** [comment]
Resolved in https://github.com/dpn-admin/dpn-server/pull/67
