### ISSUE TITLE
Evaluate adding an app version

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#66]
Might modify and use https://github.com/dpn-admin/rails-app-versioning

**Comment by malakai97** [comment]
I get a 404

**Comment by malakai97** [comment]
https://github.com/dpn-admin/dpn-server/blob/master/config/initializers/version.rb exists, does this address this need?

**Comment by dazza-codes** [comment]
It depends on the purpose of the value stored in https://github.com/dpn-admin/dpn-server/blob/master/config/initializers/version.rb - it seems to be simply an API version number, at present.  The goal of this issue is to provide a semantic version, i.e. http://semver.org/, which could be placed in `config/version.rb`

**Comment by dazza-codes** [comment]
See also http://stackoverflow.com/questions/11199553/where-to-define-rails-apps-version-number

**Comment by malakai97** [comment]
This enhancement is welcome but not required.  The PR would be accepted provided it accounts for where version is used.

**Comment by dazza-codes** [comment]
Leaving this open to work on a PR for it.  We plan to use an app version for monitoring/tracking dependency and security issues on prod systems.

**Comment by malakai97** [comment]
Info: 
- VERSION is set in `config/initializers/version.rb` 
- used in `config/routes.rb`
- used in `spec/routing/member_routes_spec.rb`

**Comment by dazza-codes** [comment]
Completed work on a gem that can help to manage a semantic version, see alpha-status code in
https://github.com/sul-dlss/app_version_tasks

Will explore using this gem in a feature branch for dpn-server.  We can't use a semantic version in the `config/initializers/version.rb` file, at it is now, because the digit in that file is used in the rails route for the API version, as in `/api-v#{version}`.
