### ISSUE TITLE
[Deployment] git submodule commands

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#71]
The swagger-ui at /api-docs is linked to code from the `dpn-rest-spec` using a git submodule.  In the parent project (this one), the submodule path is empty.  It is populated after cloning this repo and issuing a `git submodule update --init --recursive` command.

So, application deployment processes must pull in the code for the `dpn-rest-spec` project in the git submodule, which looks something like this:

``` sh
$ git clone https://github.com/dpn-admin/dpn-server.git dpn-admin/dpn-server
Cloning into 'dpn-admin/dpn-server'...

$ cd dpn-admin/dpn-server

$ git submodule update --init --recursive
Submodule 'dpn-rest-spec' (https://github.com/dpn-admin/dpn-rest-spec.git) registered for path 'dpn-rest-spec'
Cloning into 'dpn-rest-spec'...
Submodule path 'dpn-rest-spec': checked out '4c1cbba135051a0a520cf183f3445a740757086a'
```

When using Capistrano, it should be taken care of with a plugin like
https://github.com/ekho/capistrano-git-submodule-strategy

Since there is no deployment code in this `dpn-server` project, this issue must be addressed by each DPN node deploying the server.  There should be an example of using Capistrano for deployment in the SDR fork of this project, see https://github.com/sul-dlss/dpn-server

**Comment by malakai97** [comment]
Should add this to the readme.

**Comment by dazza-codes** [comment]
Moved this documentation to the wiki at https://github.com/dpn-admin/dpn-server/wiki/Deployment-for-dpn-server
