### ISSUE TITLE
Establish peer connectivity

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/dpn-server#95]
## Each node must verify that it has peer node connectivity for:
- the DPN API 
- Rsync 

DPN-dev nodes:
- [ ] APTrust
- [x] Chronopolis
- [x] Hathi
- [x] SDR
- [x] TDR

**Comment by dazza-codes** [comment]
SDR-dev connectivity issue is in https://github.com/dpn-admin/dpn-sync/issues/27

**Comment by malakai97** [comment]
HathiTrust connections to DPN-dev nodes
- [x] HTTPS connections
  - [x] APTrust
    - [x] -> APTrust
    - [x] APTrust ->
  - [x] Chronopolis
    - [x] -> Chron
    - [x] Chron -> 
  - [x] Hathi
    - [x] -> Hathi
    - [x] Hathi ->
  - [x] TDR
    - [x] -> TDR
    - [x] TDR ->
  - [x] SDR
    - [x] -> SDR
    - [x] SDR ->
- [x] SSH/RSYNC connections
  - [x] -> APTrust
  - [x] -> Chron 
  - [x] -> Hathi
  - [x] -> TDR
  - [x] -> SDR

**Comment by dazza-codes** [comment]
The SDR-dev node is now fully connected to DPN-dev nodes.

**Comment by mikejritter** [comment]
As of this morning the Chronopolis dev node can now connect to all other DPN dev nodes via https/ssh.

**Comment by Pcolar** [comment]
Frank Smutniak:
TDR has https connectivity to each node.
TDR has ssh connectivity to sdr and chron.
TDR ssh connectivity not confirmed for hathi nor aptrust.

**Comment by smutniak** [comment]
TDR has https connectivity to each node.
TDR has ssh connectivity to sdr and chron.
TDR ssh connectivity not yet confirmed for hathi or aptrust.

**Comment by diamondap** [comment]
APTrust can connect to the HTTPS servers in all the demo environments and get a 200 response.

We can connect via SSH to all dev nodes, except Hathi. Hathi staging gives us "connection refused." Hathi production asks for a password when we connect via SSH. It should accept our key and not ask for a password.

**Comment by smutniak** [comment]
TDR's rest-dev can https connect to all dev nodes
TDR can ssh connect to all nodes but hathi
