### ISSUE TITLE
Ingest Node functionality Tests

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/dpn-server#96]
## Given a set of known small bags:

```
    * validate the bags
    * Create bag records at each ingest node 
    * Create replication requests for each replicating node 
    * Cancel at least one of the replication requests 
    * Monitor replication requests for completion or failure
```

**Comment by dazza-codes** [comment]
SDR-dev node is a replication-only node, by design, at this time.  So there is no intention, yet, to develop and test the DPN ingest functionality.

**Comment by diamondap** [comment]
APTrust has all of this functionality working, except for "Monitor replication requests for completion or failure." We currently have no automated monitoring, but we should be able to add that in the next few weeks. Until then, monitoring is by human intervention.

**Comment by mikejritter** [comment]
Chronopolis now has this functionality working with the exception of monitoring for failed replications.
