### ISSUE TITLE
Replicating Node Functionality Tests

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/dpn-server#97]
## poll ingest nodes for replication requests

```
* retrieve replication requests 
* step through status changes in the requests 
* cancel at least one request 
* reject at least one request 
* complete the remaining requests successfully 
```

**Comment by diamondap** [comment]
All of these features are working at APTrust against our local cluster.

**Comment by dazza-codes** [comment]
The dpn-sync project has unit test for most of this and we have confirmed that SDR-dev is able to:
- [x] retrieve replication requests (for its replication_from nodes)
  - replication requests are filtered by values for from-node, to-node, canceled, store-requested, stored
- [x] step through status changes in the requests
  - dpn-sync can validate bag transfer and update fixity to receive store-requested:true
  - dpn-sync can transfer staging data to a storage path and update the stored attribute
- [ ] cancel at least one request
  - this is not yet implemented, see https://github.com/dpn-admin/dpn-sync/issues/26
- [ ] reject at least one request
  - this is not yet implemented, see https://github.com/dpn-admin/dpn-sync/issues/26
- [x] complete the remaining requests successfully
