### ISSUE TITLE
Node Functionality Tests

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/dpn-server#98]
## All Nodes
- synchronize the registry with peer nodes 
  - retrieve and store the results of queries (Google doc?) for: 
    - Bag 
    - Ingest 
    - Replication 
    - Digest 
    - Fixity

Components:
- [ ] #96 Ingest functionality
- [ ] #97 Replication functionality

**Comment by dazza-codes** [comment]
SDR-dev system requires additional workers to handle some of these queries, tracked in
https://github.com/dpn-admin/dpn-sync/issues/28

**Comment by diamondap** [comment]
These features are working at APTrust, running against a local DPN cluster.

**Comment by mikejritter** [comment]
Testing against the TDR I can create/update Bags and Replications. Still need to tests again Ingest, Digest, and Fixity.

**Comment by dazza-codes** [comment]
SDR-dev has been updated to resolve https://github.com/dpn-admin/dpn-sync/issues/28 and to fix a bug in DPN bag transfers.
